name: Autotests

on:
  workflow_dispatch:
  push:
    branches: [ "master", "v1-series" ]
  pull_request:
    branches: [ "master", "v1-series" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

  # Commit identifier for good version of QReadable (tag or commit sha)
  QREADABLE_COMMIT: 8fbafab3e3ebf646b9e1d295a36d9731e736f883

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cscarney/syndic-builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=/opt/kde/usr -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
